services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
      - 9229:9229
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      DJANGO_DEV: "true"
    volumes:
      - ./backend:/app