services:
  db:
    image: postgres:15.17-trixie
    environment:
      POSTGRES_DB: hvac
      POSTGRES_USER: hvac
      POSTGRES_PASSWORD: hvac
    ports:
      - 5432:5432

  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: postgres://hvac:hvac@db:5432/hvac
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: dev
      VITE_API_URL: http://localhost:8000
    ports:
      - 5173:5173
