services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - 5173:5173
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/buildingsystem/db.sqlite3:/app/buildingsystem/db.sqlite3
