# Generated by Django 4.2.6 on 2023-11-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('density', models.FloatField()),
                ('heat_capacity', models.FloatField()),
                ('cfm', models.FloatField()),
                ('specific_heat', models.FloatField()),
                ('btu', models.FloatField()),
                ('pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Damper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField()),
                ('area', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('velocity', models.FloatField()),
                ('max_velocity', models.FloatField()),
                ('min_velocity', models.FloatField()),
                ('fan_sts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('volume', models.FloatField()),
                ('air', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hvac.air')),
            ],
        ),
        migrations.CreateModel(
            name='AirUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_air_flow', models.FloatField()),
                ('outdoor_air_flow', models.FloatField()),
                ('cooling_coil', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooling_coil', to='hvac.coil')),
                ('ea_damper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ea_damper', to='hvac.damper')),
                ('heating_coil', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heating_coil', to='hvac.coil')),
                ('ma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ma_air', to='hvac.air')),
                ('ma_damper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ma_damper', to='hvac.damper')),
                ('oa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oa_air', to='hvac.air')),
                ('oa_damper', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='oa_damper', to='hvac.damper')),
                ('ra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ra_air', to='hvac.air')),
                ('return_fan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ra_fan', to='hvac.fan')),
                ('sa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sa_air', to='hvac.air')),
                ('supply_fan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sa_fan', to='hvac.fan')),
            ],
        ),
    ]
