# Generated by Django 4.2.6 on 2023-11-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
