# Generated by Django 4.2.6 on 2023-11-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0003_alter_air_btu_alter_air_cfm_alter_air_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='btu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='air',
            name='humidity',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='air',
            name='pressure',
            field=models.FloatField(default=0.4),
        ),
        migrations.AlterField(
            model_name='air',
            name='temp',
            field=models.FloatField(default=72),
        ),
    ]
