# Generated by Django 4.2.6 on 2023-11-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0004_alter_air_btu_alter_air_humidity_alter_air_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='air',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AddField(
            model_name='airunit',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AddField(
            model_name='coil',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AddField(
            model_name='damper',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AddField(
            model_name='fan',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='Empty', max_length=100),
        ),
    ]
