# Generated by Django 4.2.6 on 2023-11-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0005_air_name_airunit_name_coil_name_damper_name_fan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airunit',
            name='return_air_flow',
            field=models.FloatField(default=38000),
        ),
    ]
