# Generated by Django 4.2.6 on 2026-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0006_airunit_return_air_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airunit',
            name='ea_damper',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='ma',
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='ma_damper',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='oa',
            field=models.FloatField(default=80),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='oa_damper',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='ra',
            field=models.FloatField(default=72),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='return_fan',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='sa',
            field=models.FloatField(default=55),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='supply_fan',
            field=models.FloatField(default=100),
        ),
    ]
