# Generated by Django 4.2.6 on 2026-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0007_alter_airunit_ea_damper_alter_airunit_ma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airunit',
            name='cooling_coil',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='airunit',
            name='heating_coil',
            field=models.FloatField(default=70),
        ),
        migrations.AlterField(
            model_name='room',
            name='air',
            field=models.FloatField(default=60),
        ),
    ]
