# Generated by Django 4.2.6 on 2026-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0008_alter_airunit_cooling_coil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airunit',
            old_name='cooling_coil',
            new_name='cooling_coil_temp',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='ea_damper',
            new_name='ea_damper_position',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='heating_coil',
            new_name='heating_coil_temp',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='ma_damper',
            new_name='ma_damper_position',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='ma',
            new_name='ma_temp',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='oa_damper',
            new_name='oa_damper_position',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='oa',
            new_name='oa_temp',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='return_fan',
            new_name='ra_fan_speed',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='return_air_flow',
            new_name='ra_flow',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='ra',
            new_name='ra_temp',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='supply_fan',
            new_name='sa_fan_speed',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='supply_air_flow',
            new_name='sa_flow',
        ),
        migrations.RenameField(
            model_name='airunit',
            old_name='sa',
            new_name='sa_temp',
        ),
        migrations.AddField(
            model_name='airunit',
            name='ma_humidity',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='airunit',
            name='oa_btu',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='airunit',
            name='oa_humidity',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='airunit',
            name='sa_btu',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='airunit',
            name='sa_humidity',
            field=models.FloatField(default=40),
        ),
    ]
