# Generated by Django 4.2.6 on 2026-03-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0009_rename_cooling_coil_airunit_cooling_coil_temp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Zone',
        ),
    ]
