# Generated by Django 4.2.6 on 2026-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0010_rename_room_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='air',
            new_name='air_temp',
        ),
        migrations.AddField(
            model_name='zone',
            name='setpoint',
            field=models.FloatField(default=65),
        ),
        migrations.AddField(
            model_name='zone',
            name='vav_dpr_pos',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='zone',
            name='vav_sa_temp',
            field=models.FloatField(default=60),
        ),
    ]
