# Generated by Django 4.2.6 on 2026-03-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0011_rename_air_zone_air_temp_zone_setpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='trend_logs',
            field=models.JSONField(default=dict),
        ),
    ]
