# Generated by Django 4.2.6 on 2026-03-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0012_zone_trend_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='airunit',
            name='ma_btu',
            field=models.FloatField(default=0),
        ),
    ]
