# Generated by Django 4.2.6 on 2026-03-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0013_airunit_ma_btu'),
    ]

    operations = [
        migrations.AddField(
            model_name='airunit',
            name='ma_flow',
            field=models.FloatField(default=0),
        ),
    ]
