# Generated by Django 5.0.1 on 2026-03-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0014_airunit_ma_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airunit',
            old_name='ma_damper_position',
            new_name='ra_damper_position',
        ),
    ]
