# Generated by Django 5.0.1 on 2026-03-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0015_rename_ma_damper_position_airunit_ra_damper_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='airunit',
            name='session_id',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='session_id',
            field=models.FloatField(default=0),
        ),
    ]
