# Generated by Django 5.0.1 on 2026-03-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvac', '0017_alter_zone_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airunit',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
